version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-docker
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=simple_forum_db
    volumes:
      - /Users/a123/go/docker-volumes/myql/db:/var/lib/mysql